name: Run Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Creates and activates venv
        run: |
            python3 -m venv ./.venv
            source ./.venv/bin/activate

      - name: Installs dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate coverage
        run: pytest --cov=app --cov-report=xml:coverage.xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Daniel-Quirino/teste-de-software