name: Run Tests and Coverage

on:
  push:
    branches:
      - main
      - alt
  pull_request:
    branches:
      - main
      - alt

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Creates and activates venv
        run: |
            python3 -m venv ./.venv
            source ./.venv/bin/activate

      - name: Installs dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate coverage
        run: pytest --cov=app tests/