name: Run Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - alt

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: python -m venv ./.venv

      - name: Activate virtual environment
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            .\.venv\Scripts\Activate.ps1
          else
            source ./.venv/bin/activate
          fi
        shell: bash

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate coverage
        run: pytest --cov=app --cov-report=xml:coverage.xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Daniel-Quirino/teste-de-software
